DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS compilations_of_events;
DROP TABLE IF EXISTS compilations;
DROP TABLE IF EXISTS participation_requests;
DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS locations;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS users (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                                     name VARCHAR(255) NOT NULL,
                                     email VARCHAR(255) NOT NULL,
                                     UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS categories (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                                     name VARCHAR(255) NOT NULL,
                                     UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS locations (
                                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                                          lat FLOAT NOT NULL,
                                          lon FLOAT NOT NULL
);

CREATE TABLE IF NOT EXISTS events (
                                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                                          annotation VARCHAR(2000) NOT NULL,
                                          category_id BIGINT REFERENCES categories(id),
                                          created_on TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                                          description VARCHAR(7000),
                                          event_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                                          initiator_id BIGINT REFERENCES users(id),
                                          location_id BIGINT REFERENCES locations(id),
                                          paid BOOLEAN NOT NULL,
                                          participant_limit BIGINT,
                                          published_on TIMESTAMP WITHOUT TIME ZONE,
                                          request_moderation BOOLEAN,
                                          state VARCHAR(55),
                                          title VARCHAR(120) NOT NULL,
                                          views BIGINT,
                                          UNIQUE (title)
);

CREATE TABLE IF NOT EXISTS participation_requests (
                                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                                          created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                                          event_id BIGINT REFERENCES events(id),
                                          requester_id BIGINT REFERENCES users(id),
                                          status VARCHAR(55),
                                          UNIQUE (event_id, requester_id)
);

CREATE TABLE IF NOT EXISTS compilations (
                                                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                                                      pinned BOOLEAN NOT NULL,
                                                      title VARCHAR(255) NOT NULL,
                                                      UNIQUE (title)
);

CREATE TABLE IF NOT EXISTS compilations_of_events (
                                                      compilation_id BIGINT REFERENCES compilations(id),
                                                      event_id BIGINT REFERENCES events(id)
);

CREATE TABLE IF NOT EXISTS comments (
                                                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                                                      created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                                                      event_id BIGINT REFERENCES events(id),
                                                      commentator_id BIGINT REFERENCES users(id),
                                                      state VARCHAR(55),
                                                      text VARCHAR(10000) NOT NULL
);